name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} for ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-13]
        arch: [auto]
        include:
          - os: ubuntu-24.04
            arch: aarch64

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        if: ${{ matrix.arch == 'aarch64' }}
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:qemu-v8.1.5

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
          CIBW_BEFORE_BUILD: "pip install -r ./requirements.txt"
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: {package}/pyproject.toml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.os }}-${{ matrix.arch }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel mypy
          pip install -U -r requirements.txt
      - name: Build distributions
        run: |
          python ./setup.py sdist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-sdist
          path: dist/*.tar.gz

  merge:
    runs-on: ubuntu-latest
    needs: [build_sdist, build_wheels]
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: all-artifacts
          pattern: artifact-*
